default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: ielts_user
  password: secret123
  pool: 5

development:
  <<: *default
  database: ielts_dev
  
test:
  adapter: sqlite3
  database: ":memory:"



production:
  url: <%= ENV["DATABASE_URL"] %>
